services:
  backend:
    build: .
    container_name: coderhaveli-backend
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      MONGO_URI: mongodb://mongodb:27017/coderhaveli
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:8
    container_name: coderhaveli-mongodb
    ports:
      - "27077:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: